### ISSUE TITLE
Custom "Parent page" dropdown option text

### ISSUE THREAD

**Issue by olivdee** [juergenweb/JkPublishPages#1]
Dear Jürgen, 

great module you created!
I am running into a special case problem though, hopefully you can help out with:

Using ProcessWire in a multidomain configuration, and each subdomain has its own "Archive" for News/Blog.
Withing your module though, one sees in the **"Parent page" dropdown** the aliases of that archive pages.
For example:
```
-------------
[Parent page]
-------------
|__archiv-neues
|__archiv-neues
|__archiv-neues
```
Could this be changed into showing as well the immediate parent one level above?
Something like: "**archiv-neues [Kindergarten XY]**", "**archiv-neues [Kindergarten YZ]**" etc.
Of course I could change the alias of each kindergarten, but my customer does not want that...

Best regards,
Dino

**Comment by juergenweb** [comment]
Hello Dino,

thanks for using this module. Your goal is very specific and I guess there will not be an easy way to achive this.

First of all, the markup for the field will be done by ProcessWire using the FieldtypePage Inputfield and not by the module, so I have no impact at all how it will be rendered.

You will find the code for the parent select here: [https://github.com/juergenweb/JkPublishPages/blob/main/JkPublishPages.module#L634](https://github.com/juergenweb/JkPublishPages/blob/main/JkPublishPages.module#L634)

This code uses the API for the FieldtypePage Class which can be found [here](https://processwire.com/api/ref/fieldtype-page/).

Maybe there is an possibility to use one of the methods, to change the title of the option to your needs.

So this is not a module related question in this case, it is a question for the forum. There are some guys who are very good in such things and maybe they can help.

I have no idea at the moment how you can achive this. Sorry!!

Best regards

**Comment by juergenweb** [comment]
Maybe this page could also be of interest for you: [https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPage/InputfieldPage.module](https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPage/InputfieldPage.module).

I guess you have to use a rendering hook for this select options field to change the markup as needed.

**Comment by juergenweb** [comment]
Hello Dino,

I have just fiddled a little bit around to get a solution and I have found one hooking into Inputfield::render:

All you need to do is to add the following code to the ready.php (Path: **site/ready.php**)

```
/**
 * Hook to add the parent page name to the label of the select input from the page select of the JKPublishPages module field
 */
$wire->addHookAfter('Inputfield::render', function(HookEvent $event) {
    $field = $event->object;

    // run only on this field
    if($field->name === 'jk_move_child'){

        // original markup of this field
        $return = $event->return;

        // extract the id of the page of the id from the option value attribute
        preg_match_all('/(<option[^>]+>)(.*?)(<\/option>)/i',$return,$result);

        // create the new options including the parent page name inside the label
        $options = [];
        foreach($result[0] as $item){

            // extract the label value of the option tag
            preg_match('/<([\w]+)[^>]*>(.*?)<\/\1>/', $item, $match);
            $label = $match[2];
            // grab the value of the option tag which contains the id
            preg_match("/value='(.*?)'/", $item, $matches);
            $id = (int)$matches[1];
            // get the page object by its id
            $page = $this->wire('pages')->get($id);
            // get the parent page object of this page
            $parent = $page->parent();
            $parentName = $parent->name;

            // replace the old label by the new one including the parent page name if parent name is not present
            if(!str_contains($label, $parentName)){
                $options[] = str_replace($label, $label.'['.$parentName.']', $item);
            } else {
                $options[] = $item;
            }

        }

        // add the new options between the old select tag
        $options = implode($options);
        $select = preg_replace('/(<select.*?>).*?(<\/select>)/', '$1'.$options.'$2', $return);

        // Populate back the return value
        $event->return = $select;

    }
});

```

This code manipulates the markup of the label of the select  - so it is a little bit dirty, because it contains a lot of preg_match, but it works in my case.
What I have done is to grab certain values (id, label) of the different pages from the markup by using preg_match function.
Then I created new option tags by adding the parent page name to the label.
As the last step I replaced the old option tags with the manipulated and put it back. 

![IMG_20230927_092824](https://github.com/juergenweb/JkPublishPages/assets/9609925/b82a0809-dcca-466c-9b53-f4dae01bd868)

In this case it adds the parent page to all pages. If you only want to add them to your desired pages (fe. archiv-neues-****), then you have to adapt the code a little bit by using fe an if condition. 

Fe. check if the page has a specific parent page - if so, add the parent page name, otherwise not:

```
// something like this
$parentpagesIds = [1043,1055,1068]; // only add the parent name to pages which have one of these parent pages
if(in_array($parentPageId,$parentpagesIds ){
  .. manipulate the label
  .. you got the idea :-)
}
```


Please let me know if it works for you.

Best regards

**Comment by juergenweb** [comment]
I have added this option now to the latest version of JkPublishPages (1.3.3).
Please update the module and you will find a new configuration setting to enable the display of the parent page inside the select.

![Screenshot 2023-09-27 at 14-01-57 Module Publish_Unpublish pages • webseite2 at](https://github.com/juergenweb/JkPublishPages/assets/9609925/a5733628-8b23-4788-9aca-d8ee233eed13)

This leads to:

![beforeafter](https://github.com/juergenweb/JkPublishPages/assets/9609925/9fc7e6bd-be1c-42ba-89c1-9588a811b789)


Now the code inside the ready.php is no longer necessary, because this hook function is now included inside the module file.

Hope this helps!

**Comment by olivdee** [comment]
Wow! Great stuff, thank you very much, it works like a charm!

All best to you


------ Original Message ------
From "juergenweb" ***@***.***>
To "juergenweb/JkPublishPages" ***@***.***>
Cc "olivdee" ***@***.***>; "Author" 
***@***.***>
Date 27.09.2023 14:05:38
Subject Re: [juergenweb/JkPublishPages] Custom "Parent page" dropdown 
option text (Issue #1)

**Comment by juergenweb** [comment]
Great to hear that! 

Just to be clear: you only need the previous parent (the page one level higher), but you do not need the root parent - it is always the closest parent?
I am asking because I have never used Processwire with multi-domain setup and therefore I have no experience.
If this is the case, I will close this issue afterwards.

Best regards
