### ISSUE TITLE
Error uploading images

### ISSUE THREAD

**Issue by ShadowMoses36** [juergenweb/JkPublishPages#3]
Hey @juergenweb 

I've discovered a new issue. Please see the screen cast at the link below, but to summarize , when a page template has this module active, uploading images break. I've checked this by disabling the module and also removing the fields from the page template. Upon doing so, image upload works once again.

A JavaScript error is shown in the console.

![Screenshot 2024-09-26 134248](https://github.com/user-attachments/assets/54f1197f-7cc6-4486-98e3-1f7c5358cb05)

See screen recording here: https://komododecks.com/recordings/WekKt1Det4OsayOzKsys

Thanks in advance

**Comment by juergenweb** [comment]
Hello @ShadowMoses36 

Thanks for reporting this issue too.

I have found the cause: There was a problem during the AJAX call of an image caused by my custom sub-headline for this module.
The headline will be output during the Ajax call too and therefore the image upload Javacript complains about the "unexpected character on line 1 column 1.

Anyway, I have fixed this now by adding an Ajax check before the output of this sub-headline and it works on my side now.
I would ask you to test this as well on your site. If it works for you, then I will bump up the module version once more.

So please replace the "JKPublishPages.module" file with the one here on Github and let me know if everything works as expected on your side.

Best regards Jürgen

**Comment by pixelsenseuk** [comment]
Hi @juergenweb 

No worries at all, I will test this out when I get home later and let you know if its okay.

Thanks again,
Wayne

**Comment by pixelsenseuk** [comment]
Hi @juergenweb 

I have tested and I can confirm it all works perfect now!

Many thanks for your swift response once again.

Wayne

**Comment by juergenweb** [comment]
Hi @ShadowMoses36 

I have bumped up the version to 1.3.12. Thanks for reporting this issue and for your feedback!
